image: python:3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

pages:
  stage: build
  script:
  - pip install pipenv
  - pipenv lock --requirements | xargs pip install
  - make gitlab-pages
  artifacts:
    paths:
    - public/
  only:
    refs:
      - master
