image: jfloff/alpine-python:3.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

pages:
  stage: build
  script:
  - pip install pipenv
  - pipenv install
  - pipenv run make gitlab-pages
  artifacts:
    paths:
    - public/
  only:
    refs:
      - master
