content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: type
        label: Type
        type: select
        options: 
          values: [ "Game", "Movie", "Book" ]
      - name: body
        label: Body
        type: rich-text
  - name: bookmarks
    label: Bookmarks
    path: content/bookmarks
    type: collection
    fields:
      - name: date
        label: Date
        type: date
        required: true
      - name: like_of
        label: URL
        type: string
      - name: title
        label: Title
        type: string