baseURL = "https://mpardalos.xyz/"
languageCode = "en-us"
title = "Michalis Pardalos"

theme = "hyde-hyde"

[params]
    themeColor = "theme-base-09"

[params.social]
    github = "mpardalos"
    linkedin = "mpardalos"
    instagram = "mpgrphoto"

[Menus]
    main = [
        { Name = "About me", URL = "/about" },
        { Name = "Current", URL = "/current" },
        { Name = "Blog", URL = "/blog" },
        { Name = "Experience/Projects", URL = "/portfolio" },
        { Name = "CV", URL = "/cv.pdf" },
        # { Name = "Gitlab", URL = "https://gitlab.com/michail_pardalos" }
    ]
