baseURL = "https://mpardalos.xyz/"
languageCode = "en-us"
title = "Michalis Pardalos"

theme = "hyde-hyde"

[params]
    description = """
    Imperial College student, functional programming enthusiast. Interested in
    all areas of computer science, but (for now) primarily programming language
    theory
    """

    themeColor = "theme-base-09"

[params.social]
    github = "mpardalos"
    gitlab = "michalis_pardalos"
    linkedin = "mpardalos"
    instagram = "mpgrphoto"

[Menus]
    main = [
        { Name = "About me", URL = "/about" },
        { Name = "Blog", URL = "/blog" },
        { Name = "Experience/Projects", URL = "/" },
        { Name = "CV", URL = "/cv.pdf" },
        # { Name = "Gitlab", URL = "https://gitlab.com/michail_pardalos" }
    ]
