[build]
publish = "public"
command = "hugo --minify"

[context.deploy-preview]
command = "hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[[redirects]]
from = "/micropub"
to = "/.netlify/functions/micropub"
status = 200

[dev]
framework = "hugo"
